# Generated by Django 3.2.5 on 2022-09-12 21:10

from django.db import migrations

def authorTransfert(apps,shema_migrations):
    Blog=apps.get_model('blog','Blog')
    User=apps.get_model('authentication','User')
    
    users=User.objects.all()
    for user in users:
        blogs=user.blog_set.all()
        for blog in blogs:
            blog.contributors.add(user,through_defaults={'participation':'auteur principal'})
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(authorTransfert)
    ]
