# Generated by Django 3.2.5 on 2022-09-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220912_2200'),
        ('blog', '0004_auto_20220912_2210'),
    ]

    operations = [
    ]
