# Generated by Django 3.2.5 on 2022-09-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_0003_auto_20220912_2200_0004_auto_20220912_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contributors',
        ),
    ]
