# Generated by Django 3.2.5 on 2022-09-10 16:14

from django.db import migrations

def create_groups(apps,shema_migration):
    group=apps.get_model('auth','Group')
    user=apps.get_model('authentication','User')
    permi=apps.get_model('auth','Permission')
    
    add_photo=permi.objects.get(codename='add_photo')
    change_photo=permi.objects.get(codename='change_photo')
    view_photo=permi.objects.get(codename='view_photo')
    delete_photo=permi.objects.get(codename='delete_photo')
    
    add_blog=permi.objects.get(codename='add_blog')
    change_blog=permi.objects.get(codename='change_blog')
    view_blog=permi.objects.get(codename='view_blog')
    delete_blog=permi.objects.get(codename='delete_blog')
    
    creators=group(name='creators')
    creators.save()
    creators.permissions.set([add_photo,change_photo,view_photo,delete_photo,add_blog,change_blog,view_blog,delete_blog])
    
    suscribers=group(name='suscribers')
    suscribers.save()
    suscribers.permissions.set([view_photo,view_blog])
    
    for use in user.objects.all():
        if use.role=='CREATOR':
            creators.user_set.add(use)
        elif use.role=='SUSCRIBER':
            suscribers.user_set.add(use)
class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
